Add utils
PaulAlbu/iteahome_amazon pull request #4
Opened 2023-12-23 13:24 UTC by Name-Alin

2023-12-23 23:29 UTC, PaulAlbu requested changes
Hei,

Am dat niste comments. Spor!

2023-12-23 23:29 UTC, PaulAlbu commented on src/main/java/ro/amazon/utils/Logger.java
> +                        + System.lineSeparator() + Arrays.toString(error.getStackTrace()),
@Name-Alin 
Hei, nu ar trebui oare sa lugam exact de unde vine eroarea prin metoda de mai jos? getStackTrace personal inca nu inteleg cum se foloseste/ mi se pare f. generata
error.printStackTrace(System.out);

2023-12-23 23:29 UTC, PaulAlbu commented on src/main/java/ro/amazon/utils/Logger.java
> +    public static void userInfo(String text) {
@Name-Alin clasa userInfo ai facut-o sa nu mai fie folosit sout?

2023-12-23 23:29 UTC, PaulAlbu commented on src/main/java/ro/amazon/utils/Logger.java
> +            if (logs.createNewFile()) {
@Name-Alin poate nu imi e mie f clar insa:
1. ` if (logs.createNewFile()) ` nu va fi totdeauna true, respectiv se va crea un file de fiecare data?

2. Mai e nevoie de else

2023-12-24 10:37 UTC, Name-Alin commented on src/main/java/ro/amazon/utils/Logger.java
> +    public static void userInfo(String text) {
asta am facut-o cand am citit unul din mesajele de la Andrei legat de logarea erorilor. Ma gandeam ca poate asa e mai clara diferenta intre ce logam catre user si ce logam pentru debug (developeri). Nu stiu daca e o idee buna.... nu tin neaparat sa facem asa, a fost o idee si am zis sa vad si parerea ta :)

2023-12-24 10:42 UTC, Name-Alin commented on src/main/java/ro/amazon/utils/Logger.java
> +            if (logs.createNewFile()) {
1. Metoda returneaza true daca fisierul nu exista si se creaza atunci cand se executa metoda asta. Daca fisierul exista, metoda returneaza false (fara sa creeze fisier nou) si merge mai departe pe else.
2. Else-ul e pe linia 22

2023-12-24 10:46 UTC, Name-Alin commented on src/main/java/ro/amazon/utils/Logger.java
> +                        + System.lineSeparator() + Arrays.toString(error.getStackTrace()),
ba da, linia 34 logheaza mesajul erorii iar pe linia 35 se logheaza stackTrace-ul - asta insemnand clasele cu linile de unde vine eroarea. Un exemplu de cum arata o eroare printata de metoda asta:
Message
[ro.amazon.ui.UserLogin.login(UserLogin.java:34), ro.amazon.Application.main(Application.java:10)]

2023-12-27 13:45 UTC, PaulAlbu commented on src/main/java/ro/amazon/utils/Logger.java
> +    public static void userInfo(String text) {
Ce zicea Andrei este sa luam mesajul care ii apare la user de la Exception/ Eroare + stack traceul .
Eu as elimina-o pe asta,  ca nu vad care ar fi valoarea :)

2023-12-27 13:50 UTC, PaulAlbu approved these changes

2023-12-27 13:58 UTC, PaulAlbu requested changes

2023-12-27 13:58 UTC, PaulAlbu commented on src/main/java/ro/amazon/dao/UserDAO.java
>              throw new IllegalStateException("Database error", e);
Aici ma uitasem, dar ar trebui sa logam IllegalStateException care are ca si cauza IOException  + mesajul de "Database error"

2023-12-29 08:31 UTC, PaulAlbu approved these changes

2023-12-29 08:32 UTC, merged

2023-12-29 08:33 UTC, PaulAlbu commented
Added create_utils as per Alin's branch